### ISSUE TITLE
How to pass parameters to LDA?

### ISSUE THREAD

**Issue by ylqfp** [intel-machine-learning/DistML#3]
Hi, I'm experimenting LDA with large scale dataset.
However, following LDA example in Example folder, I tried to pass parameters to LDA in spark-submit, there comes the error. "Unrecognized option"
My question is how to pass perameter to LDA?
## Thanks!

spark-submit --master yarn-client --class com.intel.distml.example.clustering.LDAExample --executor-memory 8G --driver-memory 8G --num-executors 500 --executor-cores 1  target/distml-0.2.jar --k 20 --input /user/xxx/distml/ldatest/input

**Comment by ylqfp** [comment]
@Yunlong-He @sunyongjie

**Comment by ylqfp** [comment]
It seems that , <input> doesnot need its option name. I removed <input> option, it seems to be working well.

**Comment by Yunlong-He** [comment]
Sorry for missing document here, we will add it soon.
here is one command example:
./spark-submit --class com.intel.distml.example.LightLDA --master yarn://dl-s1:8088 /home/spark/yunlong/distml-0.2.jar --psCount 5 --maxIterations 10 --k 5000 --alpha 0.01 --beta 0.01 --batchSize 100 --showPlexity false /data/wiki/wiki_100000

for detail options, please check LightLDA.scala.

**Comment by ylqfp** [comment]
@Yunlong-He Thanks!
By the way, how to set psCount/batchSize/partitions considering data scale?
For example, my dataset is 5000W docs, 100w uniq words. 
The cluster scale is 700 nodes, 20T memories.

**Comment by ylqfp** [comment]
I'd like to test LDA up to about billion docs in the future. 
So is there any guide on how to set up `scale` related parameters?
Thanks again.

**Comment by Yunlong-He** [comment]
there are several parameters related to scalability:
1. --num-executors
2. --executor-memory
3. --executor-cores
4. --psCount
5. --partitions
6. --batchSize
7. --trainType (if supported, not all algorithms support it now)
8. --psBackup (fault tolerance, new feature, not fully tested)

if your dataset is huge, I suggest you run from fewer parameter server and executors, for example, psCount<10, num-executors \* executor-cores < 30, and provide sufficient memory for executors. for LDA, you can also use smaller batchSize (<10000) to make it run smoothly.

If with above settings, your application can run smoothly(but may be slow), you can increase num-executors and batchSize to get higher speed.

anyway, you may met issues like OOM or HANG， which may be caused by Spark itself, or by DistML, we have to investigate it case by case,

**Comment by ylqfp** [comment]
Thanks for your advice!
I've met several OOM problems , and successfully solve them in the past.
However, HANG problem is FATAL, I couldn't find the solution, so i decided to abandon spark originated lda, turned to Distml LDA.
Currently, I'm testing a dataset of 50w docs \* 7w words, it seems to be well running. However, I don't know which iteration is it.

**Comment by ylqfp** [comment]
Problems clear, plz help close this issue. 
Thanks!
